apiVersion : apps/v1
kind: Deployment
metadata:
  name: juiceshop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop 
    spec:
      containers:
        - name: juiceshop 
          image: acreg2024.azurecr.io/juiceshop
          ports:
          - containerPort: 3000